# Generated by Django 3.2 on 2021-04-13 08:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_file_server', '0003_alter_podcast_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='participants',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100), default=0, max_length=1010, size=10),
        ),
    ]
